<?php

namespace App;

use App\DependencyInjection\FeatureFlagsExtension;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function build(ContainerBuilder $container): void
    {
        parent::build($container); // TODO: Change the autogenerated stub

        $featurFlagsExtension = new FeatureFlagsExtension();
        $container->registerExtension($featurFlagsExtension);
        $container->loadFromExtension($featurFlagsExtension->getAlias());
    }
}
